### ISSUE TITLE
Failed to run the sample code

### ISSUE THREAD

**Issue by LFCoin** [AI4Finance-Foundation/FinRL#401]
Hi, 

I am trying to run the sample code. But failed with this issue. I tried to use my code to clean Nan. But still with no luck. Please help. Thank you.

Attempted solution:
processed_full.dropna(axis=0,inplace=True)

Result:
Issue remains. 

File:  
FinRL_StockTrading_Fundamental.ipynb

Line of code: 
trained_a2c = agent.train_model(model=model_a2c, 
                             tb_log_name='a2c',
                             total_timesteps=100000)

Error message: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-76-e000b3012843> in <module>()
      1 trained_a2c = agent.train_model(model=model_a2c, 
      2                              tb_log_name='a2c',
----> 3                              total_timesteps=100000)

8 frames
/usr/local/lib/python3.7/dist-packages/torch/distributions/distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     54                 if not valid.all():
     55                     raise ValueError(
---> 56                         f"Expected parameter {param} "
     57                         f"({type(value).__name__} of shape {tuple(value.shape)}) "
     58                         f"of distribution {repr(self)} "

ValueError: Expected parameter loc (Tensor of shape (1, 30)) of distribution Normal(loc: torch.Size([1, 30]), scale: torch.Size([1, 30])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan]], device='cuda:0')

**Comment by rayrui312** [comment]
Thanks for reporting it. We have tested it and reproduced the error. We are debugging now.

**Comment by ExtEEd** [comment]
The problem is in **'log_volume'** parameter. When I exclude it from information_cols - all working.
`information_cols = ['daily_variance', 'change', 'log_volume', 'close', 'day', 'macd', 'rsi_30', 'cci_30', 'dx_30', 'turbulence']`

**Comment by LFCoin** [comment]
Hi. there is no information_cols in the file of FinRL_StockTrading_Fundamental.ipynb. Is this the correct fix?

**Comment by rayrui312** [comment]
It is fixed now. Inf values in the data cause the error. Replacing them with 0 solves the issue.

**Comment by richardhuo** [comment]
我在使用A股的数据时也发生这个问题了。 
FinRL_PortfolioAllocation_NeurIPS_2020.ipynb
Tushare 下载的数据。 如果股票中添加了 000100.SZ (TCL)或者 000998.SZ (隆平高科）就会报错。 我其他添加40+支沪深股票都没有问题。 现在就在小心翼翼地慢慢添加股票来测试。

ValueError: Expected parameter loc (Tensor of shape (1, 30)) of distribution Normal(loc: torch.Size([1, 30]), scale: torch.Size([1, 30])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
nan, nan, nan, nan, nan, nan]], device='cuda:0')

**Comment by richardhuo** [comment]
trained_a2c = agent.train_model(model=model_a2c,
tb_log_name='a2c',
total_timesteps=100000)

**Comment by rayrui312** [comment]
> 我在使用A股的数据时也发生这个问题了。 FinRL_PortfolioAllocation_NeurIPS_2020.ipynb Tushare 下载的数据。 如果股票中添加了 000100.SZ (TCL)或者 000998.SZ (隆平高科）就会报错。 我其他添加40+支沪深股票都没有问题。 现在就在小心翼翼地慢慢添加股票来测试。
> 
> ValueError: Expected parameter loc (Tensor of shape (1, 30)) of distribution Normal(loc: torch.Size([1, 30]), scale: torch.Size([1, 30])) to satisfy the constraint Real(), but found invalid values: tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]], device='cuda:0')

这个错误通常是因为state里出现了nan和inf值导致的。你可以尝试一下把nan和inf值都换成0，看是否还有这个报错。
This error is usually caused by the nan and inf values in the states. You may try to replace nan and inf values with 0s and see if there is still this error.

**Comment by mbessalle** [comment]
Issue is NOT FIXED. Even though the ratios are cleaned of NaN's and 0's, there is still a value of "inf" y the value "PB" in the ratio list. I just took it out and now works. It is in 5-2 SET UP THE TRAINING ENV and should look like this:

ratio_list = ['OPM', 'NPM','ROA', 'ROE', 'cur_ratio', 'quick_ratio', 'cash_ratio', 'inv_turnover','acc_rec_turnover', 'acc_pay_turnover', 'debt_ratio', 'debt_to_equity', 'PE', 'Div_yield'] so no "PB"

**Comment by heavy163** [comment]
> 你好，这个问题你怎么解决的呢？
