### ISSUE TITLE
FinRL_PaperTrading_Demo - IndexError: index 5846 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by boyblinky** [AI4Finance-Foundation/FinRL#423]
Hello. I'm trying to recreate the steps performed in the medium article (https://medium.datadriveninvestor.com/a-data-scientists-approach-for-algorithmic-trading-using-deep-reinforcement-learning-an-be8da40b2230). I'm using Ubuntu 18, through WLS on Windows 10, Python 3.9. I get the following error when I call either of the "train" functions.

train(start_date = '2021-10-11', 
      end_date = '2021-10-15',
      ticker_list = ticker_list, 
      data_source = 'alpaca',
      time_interval= '1Min', 
      technical_indicator_list= TECHNICAL_INDICATORS_LIST,
      drl_lib='elegantrl', 
      env=env,
      model_name='ppo', 
      API_KEY = API_KEY, 
      API_SECRET = API_SECRET, 
      APCA_API_BASE_URL = APCA_API_BASE_URL,
      erl_params=ERL_PARAMS,
      cwd='./papertrading_erl', #current_working_dir
      break_step=1e5)

Alpaca successfully connected
Data before 2021-10-11T15:59:00-04:00 is successfully fetched
Data before 2021-10-12T15:59:00-04:00 is successfully fetched
Data before 2021-10-13T15:59:00-04:00 is successfully fetched
Data before 2021-10-14T15:59:00-04:00 is successfully fetched
Data before 2021-10-15T15:59:00-04:00 is successfully fetched
The price of the first row for ticker  AXP  is NaN.  It will filled with the first valid price.
The price of the first row for ticker  TRV  is NaN.  It will filled with the first valid price.
Data clean finished!
Succesfully add technical indicators
Data before 2021-10-11T15:59:00-04:00 is successfully fetched
Data before 2021-10-12T15:59:00-04:00 is successfully fetched
Data before 2021-10-13T15:59:00-04:00 is successfully fetched
Data before 2021-10-14T15:59:00-04:00 is successfully fetched
Data before 2021-10-15T15:59:00-04:00 is successfully fetched
Data clean finished!
Successfully transformed into array
| Arguments Remove cwd: ./papertrading_erl
################################################################################
ID     Step    maxR |    avgR   stdR   avgS  stdS |    expR   objC   etc.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_10812/3052588872.py in <module>
----> 1 train(start_date = '2021-10-11', 
      2       end_date = '2021-10-15',
      3       ticker_list = ticker_list,
      4       data_source = 'alpaca',
      5       time_interval= '1Min',

~/FinRL/finrl/train.py in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     51 
     52         model = agent.get_model(model_name, model_kwargs=erl_params)
---> 53         trained_model = agent.train_model(
     54             model=model, cwd=cwd, total_timesteps=break_step
     55         )

~/FinRL/finrl/drl_agents/elegantrl/models.py in train_model(self, model, cwd, total_timesteps)
     79         model.cwd = cwd
     80         model.break_step = total_timesteps
---> 81         train_and_evaluate(model)
     82 
     83     @staticmethod

~/anaconda3/lib/python3.9/site-packages/elegantrl/train/run.py in train_and_evaluate(***failed resolving arguments***)
     39 
     40         torch.set_grad_enabled(True)
---> 41         logging_tuple = agent.update_net(buffer, batch_size, repeat_times, soft_update_tau)
     42         torch.set_grad_enabled(False)
     43 

~/anaconda3/lib/python3.9/site-packages/elegantrl/agents/AgentPPO.py in update_net(self, buffer, batch_size, repeat_times, soft_update_tau)
    187             buf_logprob = self.act.get_old_logprob(buf_action, buf_noise)
    188 
--> 189             buf_r_sum, buf_adv_v = self.get_reward_sum(buf_len, buf_reward, buf_mask, buf_value)  # detach()
    190             buf_adv_v = (buf_adv_v - buf_adv_v.mean()) * (self.lambda_a_value / (buf_adv_v.std() + 1e-5))
    191             # buf_adv_v: buffer data of adv_v value

~/anaconda3/lib/python3.9/site-packages/elegantrl/agents/AgentPPO.py in get_reward_sum_raw(self, buf_len, buf_reward, buf_mask, buf_value)
    237         pre_r_sum = 0
    238         for i in range(buf_len - 1, -1, -1):
--> 239             buf_r_sum[i] = buf_reward[i] + buf_mask[i] * pre_r_sum
    240             pre_r_sum = buf_r_sum[i]
    241         buf_adv_v = buf_r_sum - buf_value[:, 0]

IndexError: index 5846 is out of bounds for dimension 0 with size 1

**Comment by rayrui312** [comment]
Thanks for reporting it. It is caused by ElegantRL. We are fixing it.

**Comment by rayrui312** [comment]
It is updated now. You may have a try.

**Comment by zhongguojie1998** [comment]
Hi it seems the issue still exists, could you please check that again? Thanks a lot!

**Comment by boyblinky** [comment]
I went back to run it again. After doing a git pull to the latest, I got a different error. I didn't get to the section were this one was. A the "Import related modules" I got 

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_153/160074372.py in <module>
----> 1 from finrl.train import train
      2 from finrl.test import test
      3 from finrl.apps.config import DOW_30_TICKER
      4 from finrl.apps.config import TECHNICAL_INDICATORS_LIST
      5 from finrl.finrl_meta.env_stock_trading.env_stocktrading_np import StockTradingEnv

~/FinRL/finrl/train.py in <module>
      1 import ray
----> 2 from finrl.drl_agents.elegantrl.models import DRLAgent as DRLAgent_erl
      3 from finrl.drl_agents.rllib.models import DRLAgent as DRLAgent_rllib
      4 from finrl.drl_agents.stablebaselines3.models import DRLAgent as DRLAgent_sb3
      5 from finrl.finrl_meta.data_processor import DataProcessor

~/FinRL/finrl/drl_agents/elegantrl/models.py in <module>
      1 # DRL models from ElegantRL: https://github.com/AI4Finance-Foundation/ElegantRL
      2 import torch
----> 3 from elegantrl.agent import AgentDDPG
      4 from elegantrl.agent import AgentPPO
      5 from elegantrl.agent import AgentSAC

ModuleNotFoundError: No module named 'elegantrl.agent'

Probably just need to reset or clear the workbook. I'll try to troubleshoot it later.

**Comment by marcipops** [comment]
I tried the latest and it gave exactly your original error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_1569/3052588872.py in <module>
----> 1 train(start_date = '2021-10-11', 
      2       end_date = '2021-10-15',
      3       ticker_list = ticker_list,
      4       data_source = 'alpaca',
      5       time_interval= '1Min',

~/anaconda3/lib/python3.9/site-packages/finrl/train.py in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     51 
     52         model = agent.get_model(model_name, model_kwargs=erl_params)
---> 53         trained_model = agent.train_model(
     54             model=model, cwd=cwd, total_timesteps=break_step
     55         )

~/anaconda3/lib/python3.9/site-packages/finrl/drl_agents/elegantrl/models.py in train_model(self, model, cwd, total_timesteps)
     79         model.cwd = cwd
     80         model.break_step = total_timesteps
---> 81         train_and_evaluate(model)
     82 
     83     @staticmethod

~/anaconda3/lib/python3.9/site-packages/elegantrl/train/run.py in train_and_evaluate(***failed resolving arguments***)
     39 
     40         torch.set_grad_enabled(True)
---> 41         logging_tuple = agent.update_net(buffer, batch_size, repeat_times, soft_update_tau)
     42         torch.set_grad_enabled(False)
     43 

~/anaconda3/lib/python3.9/site-packages/elegantrl/agents/AgentPPO.py in update_net(self, buffer, batch_size, repeat_times, soft_update_tau)
    187             buf_logprob = self.act.get_old_logprob(buf_action, buf_noise)
    188 
--> 189             buf_r_sum, buf_adv_v = self.get_reward_sum(buf_len, buf_reward, buf_mask, buf_value)  # detach()
    190             buf_adv_v = (buf_adv_v - buf_adv_v.mean()) * (self.lambda_a_value / (buf_adv_v.std() + 1e-5))
    191             # buf_adv_v: buffer data of adv_v value

~/anaconda3/lib/python3.9/site-packages/elegantrl/agents/AgentPPO.py in get_reward_sum_raw(self, buf_len, buf_reward, buf_mask, buf_value)
    237         pre_r_sum = 0
    238         for i in range(buf_len - 1, -1, -1):
--> 239             buf_r_sum[i] = buf_reward[i] + buf_mask[i] * pre_r_sum
    240             pre_r_sum = buf_r_sum[i]
    241         buf_adv_v = buf_r_sum - buf_value[:, 0]

IndexError: index 5846 is out of bounds for dimension 0 with size 1

**Comment by marcipops** [comment]
Exactly the same environment setup that boyblinky had originally -  Ubuntu 18, through WLS on Windows 10, Python 3.9.7

**Comment by rayrui312** [comment]
Have you updated to the newest version of FinRL and ElegantRL (the GitHub versions)? I have tested it just now. It works in Colab. Issue #423 should be fixed by the updates of `finrl/drl_agents/elegantrl/models.py` 5 days ago. 

This notebook should work by replacing the alpaca account info with yours. You may have a test. Please notify me if there are still errors.

**Comment by marcipops** [comment]
rayrui312 yes updated to newest version of FinRL and ElegantRL (the GitHub versions).  Runs in Colab fine - see issue I reported #412 which I have closed.

However, confirmed it fails on Ubuntu 18, through WLS on Windows 10, Python 3.9.7 with this issue #423.  Please can you confirm?

**Comment by rayrui312** [comment]
> rayrui312 yes updated to newest version of FinRL and ElegantRL (the GitHub versions). Runs in Colab fine - see issue I reported #412 which I have closed.
> 
> However, confirmed it fails on Ubuntu 18, through WLS on Windows 10, Python 3.9.7 with this issue #423. Please can you confirm?

Can you try it in python 3.6, 3.7, or 3.8? We have not supported python 3.9 yet. I am not sure whether it can work in python 3.9.

**Comment by marcipops** [comment]
I have completely reinstalled from with Python 3.8 but still fails to run Test section.

These are exactly the steps I took from when it failed above and after your advice to create an environment for python 3.8
Followed https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159 and selected Windows/Ubuntu option.

After Anaconda installed then:
conda create -n FinRL python=3.8
conda activate FinRL
conda install -c conda-forge jupyterlab
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx
pip install git+https://github.com/AI4Finance-
git clone https://github.com/AI4Finance-
sudo apt install swig gcc
sudo apt-get update
sudo apt-get install --reinstall build-essential
jupyter notebook
Ran FinRL_PaperTrading.pynb

Error is below ....
Test
In [20]:
account_value_erl=test(start_date = TEST_START_DATE, 
                      end_date = TEST_END_DATE,
#account_value_erl=test(start_date = '2021-10-18', #MH updated
#                      end_date = '2021-10-19',    #MH updated
                      ticker_list = ticker_list, 
                      data_source = 'alpaca',
                      time_interval= '1Min', 
                      technical_indicator_list= TECHNICAL_INDICATORS_LIST,
                      drl_lib = DRL_LIB, #MH added
#                      drl_lib='elegantrl',
                      env=env, 
                      model_name='ppo', 
                      API_KEY = API_KEY, 
                      API_SECRET = API_SECRET, 
                      APCA_API_BASE_URL = APCA_API_BASE_URL,
                      cwd='./papertrading_erl',
                      net_dimension = 512)
Alpaca successfully connected
Data before 2022-01-08T15:59:00-05:00 is successfully fetched
Data before 2022-01-09T15:59:00-05:00 is successfully fetched
Data clean finished!
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-20-b3649e12e03b> in <module>
----> 1 account_value_erl=test(start_date = TEST_START_DATE, 
      2                       end_date = TEST_END_DATE,
      3 #account_value_erl=test(start_date = '2021-10-18', #MH updated
      4 #                      end_date = '2021-10-19',    #MH updated
      5                       ticker_list = ticker_list,

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/finrl/test.py in test(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     36     data = DP.download_data(ticker_list, start_date, end_date, time_interval)
     37     data = DP.clean_data(data)
---> 38     data = DP.add_technical_indicator(data, technical_indicator_list)
     39 
     40     if if_vix:

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/finrl/finrl_meta/data_processor.py in add_technical_indicator(self, df, tech_indicator_list)
     48     def add_technical_indicator(self, df, tech_indicator_list) -> pd.DataFrame:
     49         self.tech_indicator_list = tech_indicator_list
---> 50         df = self.processor.add_technical_indicator(df, tech_indicator_list)
     51 
     52         return df

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/finrl/finrl_meta/data_processors/processor_alpaca.py in add_technical_indicator(self, df, tech_indicator_list)
    135         df = df.rename(columns={"time": "date"})
    136         df = df.copy()
--> 137         df = df.sort_values(by=["tic", "date"])
    138         stock = Sdf.retype(df.copy())
    139         unique_ticker = stock.tic.unique()

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/core/frame.py in sort_values(self, by, axis, ascending, inplace, kind, na_position, ignore_index, key)
   6240         if len(by) > 1:
   6241 
-> 6242             keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
   6243 
   6244             # need to rewrap columns in Series to apply key function

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/core/frame.py in <listcomp>(.0)
   6240         if len(by) > 1:
   6241 
-> 6242             keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
   6243 
   6244             # need to rewrap columns in Series to apply key function

~/anaconda3/envs/FinRL/lib/python3.8/site-packages/pandas/core/generic.py in _get_label_or_level_values(self, key, axis)
   1777             values = self.axes[axis].get_level_values(key)._values
   1778         else:
-> 1779             raise KeyError(key)
   1780 
   1781         # Check for duplicates

KeyError: 'tic'

**Comment by marcipops** [comment]
This issue is related to issue #420.  I have tried complete reinstall with python 3.8 and it breaks on the Test section

**Comment by florian-guily** [comment]
Hi i also have this issue on WSL on windows 10 on ubuntu 20.04 but it works fine on colab too. I use the latest version of finrl from pypi (i did pip install finrl).

**Comment by marcipops** [comment]
Jingyang and I eventually managed to get it working.

This Source is used but will need to be updated: https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159

Install Ubuntu
Windows Store
Select Ubuntu 18.04 LTS
Install
Unix Username: XXX
Password: XXX
Check Ubuntu release:
lsb_release -a
Results in:
No LSB modules are available.
Distributor ID: Ubuntu
Description:   Ubuntu 18.04.5 LTS
Release:       18.04
Codename:      bionic
Install Anaconda
https://linuxize.com/post/how-to-install-anaconda-on-ubuntu-18-04/
#Jingyang installed this version: https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh
cd /tmp
curl -O https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh
sha256sum Anaconda3-5.2.0-Linux-x86_64.sh
bash Anaconda3-5.2.0-Linux-x86_64.sh
Do you wish to proceed with the installation of Microsoft VSCode? [yes|no]
>>> no
source ~/.bashrc
conda update conda
conda update anaconda
Create environment
conda create -n marc python==3.8.12                #jingyang said he used 'conda create -n name python==3.8.12'
Exit Ubuntu,
Login Ubuntu
Conda activate marc
sudo apt install swig
sudo apt-get install g++
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx
pip install git+ https://github.com/AI4Finance-Foundation/FinRL.git
git clone https://github.com/AI4Finance-Foundation/FinRL.git
sudo apt install jupyter-core
pip install jupyter
python -m ipykernel install --user --name marc             ##Install kernelspec marc in /home/marc/.local/share/jupyter/kernels/marc
pip install dm_tree
Jupyter notebook

Ran the papertrading demo and it worked.

You might be to achieve a better or more compact set of instructions, so please share - but at least you know this set worked on my PC and replicated on Jingyangs.
Hope that helps.  Not sure of the root cause but think it might be the version of Python (I originally was using 3.9).
